baseurl: ''
permalink: pretty
title: 'MediOpto'
description: 'Medical equipment and services provider specializing in optical and diagnostic solutions.'
url: 'https://wallabbb.github.io'

logo: '/images/logo/logo.svg'
logo_mobile: '/images/logo/logo-mobile.svg'

# Collections
collections:
  services:
    output: true
    permalink: /services/:path/

# Default author settings
author:
  name: 'Your Name'
  image: '/images/author.jpg'

# Footer
footer:
  copyright_text: 'Â© 2024 MediOpto. All rights reserved.'

# Configure Jekyll to include _pages directory
include:
  - _pages

sass:
  style: compressed

plugins:
  - jekyll-environment-variables
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
